# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Apache2-ASP
version:      1.01
version_from: lib/Apache2/ASP.pm
installdirs:  site
requires:
    Apache::Test:                  
    CGI:                           
    CGI::Apache2::Wrapper:         
    Cwd:                           
    DateTime::Duration:            
    DBD::SQLite:                   
    DBI:                           
    Devel::StackTrace:             
    Digest::MD5:                   
    HTTP::Date:                    
    Mail::Sendmail:                
    MIME::Types:                   
    Storable:                      
    Sys::Hostname:                 
    XML::Simple:                   

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
