# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Apache2-ASP
version:      1.27
version_from: lib/Apache2/ASP.pm
installdirs:  site
requires:
    Apache2::Directive:            0
    Apache::Test:                  0
    CGI:                           0
    CGI::Apache2::Wrapper:         0
    CGI::Simple:                   0
    Cwd:                           0
    DateTime::Duration:            0
    DBD::SQLite:                   0
    DBI:                           0
    Devel::StackTrace:             0
    Digest::MD5:                   0
    HTML::Form:                    0
    HTTP::Date:                    0
    HTTP::Request::AsCGI:          0
    Ima::DBI:                      0.35
    Mail::Sendmail:                0
    MIME::Types:                   0
    Storable:                      0
    Sys::Hostname:                 0
    XML::Simple:                   0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
