# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Apache2-ASP
version:      0.03
version_from: lib/Apache2/ASP.pm
installdirs:  site
requires:
    Apache2::Const:                2.000002
    Apache::Test:                  
    CGI::Apache2::Wrapper:         0.21
    Cwd:                           
    DBD::SQLite:                   1.13
    DBI:                           1.5
    Devel::StackTrace:             
    Digest::MD5:                   
    HTTP::Date:                    1.47
    Mail::Sendmail:                
    Storable:                      
    Test::More:                    
    XML::Simple:                   

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
