--- #YAML:1.0
name:                Apache2-ASP
version:             1.48
abstract:            ~
license:             ~
author:              
    - John Drago <jdrago_999@yahoo.com>
generated_by:        ExtUtils::MakeMaker version 6.44
distribution_type:   module
requires:     
    Apache2::Directive:            0
    CGI::Apache2::Wrapper:         0
    CGI::Simple:                   0
    Cwd:                           0
    Data::Properties::YAML:        0.02
    DateTime::Duration:            0
    DBD::SQLite:                   0
    DBI:                           0
    Devel::StackTrace:             0
    Digest::MD5:                   0
    HTML::Form:                    0
    HTTP::Body:                    1.01
    HTTP::Date:                    0
    HTTP::Request::AsCGI:          0
    Ima::DBI:                      0.35
    Mail::Sendmail:                0
    MIME::Types:                   0
    Storable:                      0
    Sys::Hostname:                 0
    Test::Exception:               0
    XML::Simple:                   0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
