# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Apache2-ASP
version:      0.01
version_from: lib/Apache2/ASP.pm
installdirs:  site
requires:
    Apache::Test:                  

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
