--- #YAML:1.0
name:                Apache2-ASP
version:             2.00_14
abstract:            ASP for Perl, reloaded.
license:             artistic
author:              
    - John Drago <jdrago_999@yahoo.com>
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    CGI::Apache2::Wrapper:         0
    CGI::Simple:                   0
    Cwd:                           0
    Data::Properties::YAML:        0.02
    DBD::SQLite:                   0
    DBI:                           0
    Devel::StackTrace:             0
    Digest::MD5:                   0
    HTML::Form:                    0
    HTTP::Body:                    1.01
    HTTP::Date:                    0
    HTTP::Request::AsCGI:          0
    Ima::DBI:                      0.35
    Mail::Sendmail:                0
    MIME::Types:                   0
    Storable:                      0
    Test::Exception:               0
    Test::More:                    0
    Time::HiRes:                   0
    XML::Parser:                   0
    XML::Simple:                   0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
